// The full agent catalog (25 core + specialist additions): presentation + seed metadata.
// This is the single source of truth for what agents exist, what category
// they belong to, and what they're supposed to do. `lib/agent-prompts.ts`
// only has system prompts for the agents marked `wired: true` here.

export const CATEGORY_ORDER = [
  "Front Office",
  "Executive & Intelligence",
  "CRM & Lead Operations",
  "Acquisition",
  "Content & Creative",
  "Digital Experience",
  "Retention & Lifecycle",
  "Marketing Operations",
  "Intelligence & Measurement",
  "Freelancer & Agency Growth",
] as const;

export type CategoryName = (typeof CATEGORY_ORDER)[number];

export const CATEGORY_COLORS: Record<CategoryName, string> = {
  "Front Office": "#8A8F86",
  "Executive & Intelligence": "#4C5FD5",
  "CRM & Lead Operations": "#2A6F97",
  Acquisition: "#1F8A5C",
  "Content & Creative": "#B5541C",
  "Digital Experience": "#0E7C86",
  "Retention & Lifecycle": "#B5388E",
  "Marketing Operations": "#6B6B47",
  "Intelligence & Measurement": "#8A3FA0",
  "Freelancer & Agency Growth": "#C2410C",
};

export interface AgentSpec {
  key: string;
  name: string;
  category: CategoryName;
  mission: string;
  inputs: string[];
  outputs: string[];
  wired: boolean;
  sortOrder: number;
}

export const AGENT_CATALOG: AgentSpec[] = [
  // Front Office
  {
    key: "receptionist-concierge",
    name: "Marketing Concierge Agent",
    category: "Front Office",
    mission: "The front door — interprets what the user is actually asking for and routes them to the right agent or workflow. Advisory triage, not a live chat interface.",
    inputs: ["User's raw request", "Company DNA"],
    outputs: ["Interpreted request", "Recommended agent(s) or workflow", "Clarifying questions if the request is ambiguous"],
    wired: true,
    sortOrder: 1,
  },
  {
    key: "client-onboarding",
    name: "Client Onboarding Agent",
    category: "Front Office",
    mission: "Determines exactly what information is still missing to onboard this client properly — company, tools, goals, budget, brand, CRM, access — and drafts the specific questions to ask. Advisory checklist, not a live intake flow.",
    inputs: ["Company DNA so far", "Industry"],
    outputs: ["Onboarding completeness score", "Prioritized question list", "Access/tooling checklist"],
    wired: true,
    sortOrder: 2,
  },
  {
    key: "meeting-summary-insights",
    name: "Meeting Summary & Insights Agent",
    category: "Front Office",
    mission: "Turns a real meeting transcript (from Zoom/Teams/Meet's own recording+transcript feature, or any transcription tool — platform-agnostic since it works from text, not a live call join) into a summary, key decisions, and action items, and auto-detects whether this is a follow-up to a past meeting stored in this workspace's history, naming which one and why. Does not join or record live calls itself — no free path exists to do that without real per-meeting infrastructure cost, confirmed before building.",
    inputs: ["Meeting transcript (required)", "Past meeting history in this workspace (automatic)"],
    outputs: ["Meeting summary", "Key decisions & action items", "Follow-up detection (which past meeting, if any, and why)"],
    wired: true,
    sortOrder: 3,
  },
  {
    key: "meeting-qa",
    name: "Meeting Q&A Agent",
    category: "Front Office",
    mission: "Answers a question about what happened across this workspace's past meetings — the \"chatbot\" experience over meeting history, built from real stored summaries (via Meeting Summary & Insights Agent), never invented. Distinct from that agent: this one answers questions about the past, it doesn't process a new transcript.",
    inputs: ["A question about past meetings", "Past meeting history in this workspace (automatic)"],
    outputs: ["An answer grounded in real stored meeting summaries", "Which specific meeting(s) it's drawn from"],
    wired: true,
    sortOrder: 4,
  },
  // Executive & Intelligence
  {
    key: "marketing-strategy",
    name: "Marketing Strategy Agent",
    category: "Executive & Intelligence",
    mission: "Synthesizes Company DNA into a concrete 90-day marketing strategy with channel priorities, budget allocation, and KPI targets.",
    inputs: ["Business model & industry", "Objective", "Monthly budget & currency", "Current channels & assets"],
    outputs: ["90-day roadmap", "Channel priorities", "Budget allocation", "KPI targets"],
    wired: true,
    sortOrder: 1,
  },
  {
    key: "market-research",
    name: "Market Research Agent",
    category: "Executive & Intelligence",
    mission: "Researches industry structure, demand drivers, and competitor landscape for the client's market and geography.",
    inputs: ["Industry", "Geography", "Objective"],
    outputs: ["Market overview", "Competitor landscape table", "Whitespace opportunities"],
    wired: true,
    sortOrder: 2,
  },
  {
    key: "icp-intelligence",
    name: "Customer / ICP Intelligence Agent",
    category: "Executive & Intelligence",
    mission: "Determines the ideal customer profile, personas, pain points, and buying triggers.",
    inputs: ["Industry", "Existing ICP notes", "Objective"],
    outputs: ["ICP definition", "2-3 personas", "Buying trigger map", "Messaging hooks"],
    wired: true,
    sortOrder: 3,
  },
  {
    key: "competitive-intelligence",
    name: "Competitive Intelligence Agent",
    category: "Executive & Intelligence",
    mission: "Analyzes competitors across website, SEO, ads, content, pricing, and positioning to find exploitable gaps.",
    inputs: ["Competitor URLs / names", "Industry", "Objective"],
    outputs: ["Competitor teardown", "Positioning gaps", "Where we're losing and why"],
    wired: true,
    sortOrder: 4,
  },
  {
    key: "needs-analyzer",
    name: "Marketing Needs Analyzer",
    category: "Executive & Intelligence",
    mission: "Decides which agents in the catalog should be active vs. idle for this client right now, and explains why.",
    inputs: ["Full Company DNA", "Agent catalog"],
    outputs: ["Activation plan (every agent)", "First three agents to run", "What would change the verdict"],
    wired: true,
    sortOrder: 5,
  },
  {
    key: "marketing-orchestrator",
    name: "Marketing Orchestrator",
    category: "Executive & Intelligence",
    mission: "Sequences active agents, resolves dependencies and conflicts, and coordinates hand-offs between them.",
    inputs: ["Active agent set", "Agent outputs so far"],
    outputs: ["Execution sequence", "Dependency graph", "Hand-off notes"],
    wired: true,
    sortOrder: 6,
  },
  {
    key: "marketing-opportunity",
    name: "Marketing Opportunity Agent",
    category: "Executive & Intelligence",
    mission: "Continuously scans for what's missing — no CRM, no tracking, weak SEO, poor follow-up — and ranks the highest-impact gaps.",
    inputs: ["Current channels", "Marketing assets", "Agent run history"],
    outputs: ["Ranked opportunity list", "Effort/impact estimate per gap"],
    wired: true,
    sortOrder: 7,
  },
  {
    key: "budget-investment",
    name: "Budget & Investment Agent",
    category: "Executive & Intelligence",
    mission: "Decides how total marketing budget should split across brand, digital, content, tech, and experiments — before Performance Marketing allocates the digital slice.",
    inputs: ["Total monthly budget & currency", "Objective", "Strategy output"],
    outputs: ["Top-level budget split", "Rationale per bucket"],
    wired: true,
    sortOrder: 8,
  },
  {
    key: "business-intelligence",
    name: "Business Intelligence Agent",
    category: "Executive & Intelligence",
    mission: "Builds a clear-eyed picture of the business itself — model, unit economics, product, industry position — before any marketing recommendation is made.",
    inputs: ["Industry", "Business model signals", "AOV/LTV/margin if provided"],
    outputs: ["Business model summary", "Unit economics read", "Key business risks marketing can't fix"],
    wired: true,
    sortOrder: 9,
  },
  {
    key: "offer-positioning-intelligence",
    name: "Offer & Positioning Intelligence Agent",
    category: "Executive & Intelligence",
    mission: "Checks whether the product, pricing, offer, and differentiation are actually strong enough to market — before blaming acquisition channels for weak conversion.",
    inputs: ["Objective", "ICP notes", "Industry"],
    outputs: ["Offer strength assessment", "Positioning gaps", "Recommended offer changes before scaling spend"],
    wired: true,
    sortOrder: 10,
  },
  {
    key: "product-marketing-gtm",
    name: "Product Marketing / GTM Agent",
    category: "Executive & Intelligence",
    mission: "Plans launch messaging, packaging, and go-to-market sequencing for a new product or feature.",
    inputs: ["Objective", "ICP/personas", "Existing positioning"],
    outputs: ["GTM plan", "Launch messaging", "Packaging recommendations"],
    wired: true,
    sortOrder: 11,
  },
  {
    key: "forecasting",
    name: "Forecasting Agent",
    category: "Executive & Intelligence",
    mission: "Projects leads, customers, revenue, and CAC forward from the stated budget and targets — labeled as a model, not a guarantee.",
    inputs: ["Monthly budget & currency", "Targets (CAC/CPL/ROAS/revenue)", "Run history"],
    outputs: ["Lead/customer/revenue forecast range", "Key assumptions", "Sensitivity to budget changes"],
    wired: true,
    sortOrder: 12,
  },
  {
    key: "customer-journey-intelligence",
    name: "Customer Journey Intelligence Agent",
    category: "Executive & Intelligence",
    mission: "Maps the complete customer journey from first awareness to purchase and beyond, identifying where this client's actual journey likely breaks.",
    inputs: ["ICP/personas", "Current channels", "Objective"],
    outputs: ["Journey stage map", "Likely drop-off points", "Moments that matter most"],
    wired: true,
    sortOrder: 13,
  },
  {
    key: "search-intent-intelligence",
    name: "Search / Intent Intelligence Agent",
    category: "Executive & Intelligence",
    mission: "Analyzes search behavior and commercial intent patterns for this client's category, distinct from keyword-level SEO execution.",
    inputs: ["Industry", "Country/region", "Objective"],
    outputs: ["Intent mix breakdown", "Commercial vs informational demand read", "Implications for channel mix"],
    wired: true,
    sortOrder: 14,
  },
  {
    key: "competitor-seo-intelligence",
    name: "Competitor SEO Intelligence Agent",
    category: "Executive & Intelligence",
    mission: "Analyzes competitor keyword rankings, content gaps, and likely link profiles — reasoned from category knowledge, not live crawl access.",
    inputs: ["Competitor names/URLs", "Industry", "Website URL"],
    outputs: ["Competitor keyword gap analysis", "Content gap opportunities", "Link profile read (validate)"],
    wired: true,
    sortOrder: 15,
  },
  {
    key: "competitor-ad-intelligence",
    name: "Competitor Ad Intelligence Agent",
    category: "Executive & Intelligence",
    mission: "Analyzes likely competitor ad messaging, creative angles, and campaign patterns — reasoned from category knowledge, not live ad-library access.",
    inputs: ["Competitor names/URLs", "Industry", "Objective"],
    outputs: ["Likely competitor ad angles", "Creative pattern read (validate)", "Differentiation opportunities"],
    wired: true,
    sortOrder: 16,
  },
  {
    key: "pricing-strategy",
    name: "Pricing Strategy Agent",
    category: "Executive & Intelligence",
    mission: "Designs pricing tiers, discounting strategy, and price-testing approach — distinct from Offer & Positioning Intelligence's broader check of whether the offer is credible.",
    inputs: ["AOV/LTV", "Gross margin", "Competitive positioning"],
    outputs: ["Pricing tier recommendations", "Discounting strategy", "Price-test design"],
    wired: true,
    sortOrder: 18,
  },
  {
    key: "marketing-calendar-campaign-planning",
    name: "Marketing Calendar / Campaign Planning Agent",
    category: "Executive & Intelligence",
    mission: "Owns the actual customer-facing campaign calendar — what launches when, across which channels — distinct from Marketing Orchestrator's agent-sequencing focus, which schedules agent work, not customer-facing campaigns.",
    inputs: ["Active agents' outputs", "Objective", "Seasonality"],
    outputs: ["Campaign calendar shape", "Channel launch sequencing", "Theme-by-month plan"],
    wired: true,
    sortOrder: 19,
  },
  {
    key: "objective-kpi",
    name: "Objective & KPI Agent",
    category: "Executive & Intelligence",
    mission: "Determines the North Star KPI, primary/secondary KPIs, guardrails, and targets from the stated business objective — the agent-facing counterpart to the Company DNA target fields, for when those fields are still blank or need reconciling with a stated objective.",
    inputs: ["Objective", "Existing targets (CAC/CPL/ROAS/revenue) if set", "Industry"],
    outputs: ["Recommended North Star KPI", "Primary & secondary KPI set", "Guardrails", "Target values by metric"],
    wired: true,
    sortOrder: 17,
  },
  // CRM & Lead Operations
  {
    key: "crm-customer-data",
    name: "CRM & Customer Data Agent",
    category: "CRM & Lead Operations",
    mission: "Designs the CRM structure a client needs — pipeline stages, lifecycle definitions, fields — advisory only, not a live connection to any CRM yet.",
    inputs: ["Business model", "Objective", "Sales motion implied by DNA"],
    outputs: ["Lifecycle stages", "Pipeline structure", "Minimum viable field set"],
    wired: true,
    sortOrder: 1,
  },
  {
    key: "lead-routing-sla",
    name: "Lead Routing & SLA Agent",
    category: "CRM & Lead Operations",
    mission: "Designs who a lead should go to and how fast, based on territory, product, language, score, and rep capacity — advisory rule design, not live lead monitoring.",
    inputs: ["Team size/capacity implied by DNA", "Geography", "Objective"],
    outputs: ["Routing rules", "Response SLA targets", "Escalation rules"],
    wired: true,
    sortOrder: 2,
  },
  {
    key: "lead-data-quality",
    name: "Lead Data Quality & Identity Agent",
    category: "CRM & Lead Operations",
    mission: "Defines deduplication, identity resolution, and validation rules that protect the accuracy of lead counts and CAC math — advisory rule design, not a live duplicate scan.",
    inputs: ["Current channels", "Business model"],
    outputs: ["Deduplication rules", "Validation rules", "Data completeness checklist"],
    wired: true,
    sortOrder: 3,
  },
  {
    key: "sales-intelligence",
    name: "Sales Intelligence Agent",
    category: "CRM & Lead Operations",
    mission: "Analyzes where leads stall after handoff to sales — response time, follow-up, show rate, lost reasons — to tell marketing whether it has a lead problem or a sales-process problem.",
    inputs: ["Team size/capacity implied by DNA", "Objective", "Run history"],
    outputs: ["Likely bottleneck diagnosis", "Response-time benchmark", "Follow-up process recommendations"],
    wired: true,
    sortOrder: 4,
  },
  {
    key: "revenue-pipeline",
    name: "Revenue & Pipeline Intelligence Agent",
    category: "CRM & Lead Operations",
    mission: "Connects Lead → MQL → SQL → Opportunity → Customer → Revenue and frames CAC, LTV, pipeline, and forecast against the client's stated budget and currency.",
    inputs: ["Monthly budget & currency", "Objective", "Run history"],
    outputs: ["Pipeline stage definitions", "CAC/LTV framework", "Revenue forecast approach"],
    wired: true,
    sortOrder: 5,
  },
  {
    key: "abm",
    name: "Account-Based Marketing Agent",
    category: "CRM & Lead Operations",
    mission: "Designs target-account selection, buying-committee mapping, and coordinated multi-channel account journeys for B2B clients running an ABM motion.",
    inputs: ["ICP/personas", "Industry", "Objective"],
    outputs: ["Account selection criteria", "Buying committee map", "Account journey plan"],
    wired: true,
    sortOrder: 6,
  },
  {
    key: "lead-enrichment",
    name: "Lead Enrichment Agent",
    category: "CRM & Lead Operations",
    mission: "Defines what firmographic/behavioral data should be appended to a raw lead record to make it usable for scoring and routing — advisory schema, not a live enrichment API call.",
    inputs: ["Business model", "ICP/personas", "Existing stack"],
    outputs: ["Enrichment field list", "Recommended enrichment sources", "Priority order"],
    wired: true,
    sortOrder: 7,
  },
  {
    key: "lead-scoring-qualification",
    name: "Lead Scoring & Qualification Agent",
    category: "CRM & Lead Operations",
    mission: "Designs a point-based or bucket lead-scoring model distinct from Lead Behaviour's conversion-probability analysis — this one defines the scoring RULES, not a live score on real leads.",
    inputs: ["ICP/personas", "Current channels", "Objective"],
    outputs: ["Scoring model (fields & weights)", "Qualification thresholds", "MQL/SQL definitions"],
    wired: true,
    sortOrder: 8,
  },
  {
    key: "sales-follow-up",
    name: "Sales Follow-up Agent",
    category: "CRM & Lead Operations",
    mission: "Designs the follow-up cadence and messaging a sales process should use after a lead is captured, distinct from Sales Intelligence's diagnostic role.",
    inputs: ["Team size/capacity", "Sales cycle days", "Current channels"],
    outputs: ["Follow-up cadence", "Message templates per touch", "Escalation triggers"],
    wired: true,
    sortOrder: 9,
  },
  {
    key: "appointment-intelligence",
    name: "Appointment Intelligence Agent",
    category: "CRM & Lead Operations",
    mission: "Analyzes and designs for appointment show-rate — reminders, confirmation flow, rescheduling — for businesses that convert via booked meetings.",
    inputs: ["Business model", "Current channels", "Objective"],
    outputs: ["Reminder cadence", "No-show reduction tactics", "Rescheduling flow"],
    wired: true,
    sortOrder: 10,
  },
  {
    key: "revenue-attribution",
    name: "Revenue Attribution Agent",
    category: "CRM & Lead Operations",
    mission: "Defines which channel/campaign gets credit for a sale — distinct from Marketing Analytics' performance tracking — using a stated attribution model, not a black box.",
    inputs: ["Current channels", "Run history", "Objective"],
    outputs: ["Recommended attribution model", "Channel credit rules", "Known blind spots"],
    wired: true,
    sortOrder: 11,
  },
  {
    key: "sales-forecasting",
    name: "Sales Forecasting Agent",
    category: "CRM & Lead Operations",
    mission: "Forecasts pipeline-to-close outcomes from current lead volume and sales cycle — distinct from the Forecasting Agent's top-of-funnel projections.",
    inputs: ["Sales cycle days", "Run history", "Revenue target"],
    outputs: ["Pipeline-to-close forecast", "Key risks to the forecast", "What would change it"],
    wired: true,
    sortOrder: 12,
  },
  {
    key: "crm-schema-custom-field",
    name: "CRM Schema & Custom Field Agent",
    category: "CRM & Lead Operations",
    mission: "Defines custom fields, custom objects, and data definitions for the CRM — narrower and more technical than CRM & Customer Data's pipeline/lifecycle design.",
    inputs: ["Business model", "CRM & Customer Data output", "Existing stack"],
    outputs: ["Custom field definitions", "Custom object recommendations", "Data type & validation rules"],
    wired: true,
    sortOrder: 13,
  },
  {
    key: "lead-management",
    name: "Lead Management Agent",
    category: "CRM & Lead Operations",
    mission: "Oversees the general lead lifecycle end to end — the umbrella view above Lead Routing, Scoring, Enrichment, and Data Quality's individual specialties.",
    inputs: ["Current channels", "Business model", "Run history across CRM agents"],
    outputs: ["Lead lifecycle overview", "Gaps between the individual CRM agents' outputs", "Operational priorities"],
    wired: true,
    sortOrder: 14,
  },
  {
    key: "sales-assignment-capacity",
    name: "Sales Assignment & Capacity Agent",
    category: "CRM & Lead Operations",
    mission: "Plans rep territory assignment and capacity load — distinct from Lead Routing & SLA's per-lead routing rules, this one plans the team structure those rules run against.",
    inputs: ["Team size/capacity implied by DNA", "Geography", "Product lines if multiple"],
    outputs: ["Territory/assignment structure", "Capacity model", "Rebalancing triggers"],
    wired: true,
    sortOrder: 15,
  },
  {
    key: "identity-resolution-dedup",
    name: "Identity Resolution & Deduplication Agent",
    category: "CRM & Lead Operations",
    mission: "Deep-dive matching and merge logic for duplicate identities across channels — a more technical, cross-system-matching companion to Lead Data Quality's broader validation rules.",
    inputs: ["Current channels", "Existing stack", "Business model"],
    outputs: ["Matching logic (what counts as 'the same person')", "Merge rules", "Cross-system identity mapping approach"],
    wired: true,
    sortOrder: 16,
  },
  {
    key: "next-best-action",
    name: "Next Best Action Agent",
    category: "CRM & Lead Operations",
    mission: "Recommends the single next action for an individual lead or customer — action-level, distinct from Omnichannel & Next-Best-Channel's channel-selection focus.",
    inputs: ["Lead/customer stage", "Run history", "Objective"],
    outputs: ["Next action recommendation framework", "Priority logic when multiple actions compete", "Owner (marketing vs sales) per action type"],
    wired: true,
    sortOrder: 17,
  },
  {
    key: "pipeline-intelligence",
    name: "Pipeline Intelligence Agent",
    category: "CRM & Lead Operations",
    mission: "Analyzes pipeline health and velocity — stage duration, stall points — distinct from Revenue & Pipeline Intelligence's CAC/LTV economic framing.",
    inputs: ["Sales cycle days", "Run history", "CRM & Customer Data pipeline structure"],
    outputs: ["Pipeline velocity read", "Stall-point diagnosis", "Health indicators to track"],
    wired: true,
    sortOrder: 18,
  },
  {
    key: "revenue-intelligence",
    name: "Revenue Intelligence Agent",
    category: "CRM & Lead Operations",
    mission: "Broader revenue performance analysis — trends, concentration risk, growth quality — distinct from Revenue Attribution's channel-credit focus and Revenue & Pipeline's forecasting focus.",
    inputs: ["Revenue target", "Run history", "AOV/LTV"],
    outputs: ["Revenue performance read", "Concentration/risk flags", "Growth quality assessment"],
    wired: true,
    sortOrder: 19,
  },
  {
    key: "sales-enablement-battlecards",
    name: "Sales Enablement / Battlecards Agent",
    category: "CRM & Lead Operations",
    mission: "Produces sales-team-facing content — competitive battlecards, objection handling scripts, talk tracks — distinct from Content Creation's customer-facing output.",
    inputs: ["Competitive Intelligence output", "ICP/personas", "Objection patterns if known"],
    outputs: ["Competitive battlecards", "Objection handling scripts", "Talk tracks by buyer stage"],
    wired: true,
    sortOrder: 20,
  },
  {
    key: "crm-data-migration-cleanup",
    name: "CRM Data Migration & Cleanup Agent",
    category: "CRM & Lead Operations",
    mission: "Plans migration off spreadsheets or a legacy CRM, and cleanup of existing messy data — a one-time-project companion to Lead Data Quality's ongoing validation rules.",
    inputs: ["Existing stack", "Business model", "Current channels"],
    outputs: ["Migration plan", "Data cleanup priorities", "Field mapping approach"],
    wired: true,
    sortOrder: 21,
  },
  {
    key: "sales-prospecting-outbound",
    name: "Sales Prospecting & Outbound Agent",
    category: "CRM & Lead Operations",
    mission: "Researches individual target accounts/contacts against the ICP and drafts personalized first-touch outbound outreach — the client's own sales team's tactical prospecting motion, distinct from ABM's program-level account selection and from the Freelancer & Agency Growth prospecting agents, which serve the operator's own pipeline, not this client's.",
    inputs: ["ICP/personas", "Target account or contact details if provided", "Objective"],
    outputs: ["Account/contact research summary", "Personalized first-touch outreach draft", "Follow-up sequence outline"],
    wired: true,
    sortOrder: 22,
  },
  {
    key: "win-loss-analysis",
    name: "Win/Loss Analysis Agent",
    category: "CRM & Lead Operations",
    mission: "Structured retrospective on why deals were actually won or lost, turning closed-deal patterns into concrete fixes for positioning, battlecards, and ICP — distinct from Sales Intelligence's forward-looking process diagnosis and Pipeline Intelligence's in-flight stage velocity.",
    inputs: ["Closed deal outcomes (won/lost) with stated reasons", "ICP/personas", "Competitive Intelligence output if available"],
    outputs: ["Win pattern summary", "Loss pattern summary", "Positioning/battlecard fixes to make"],
    wired: true,
    sortOrder: 23,
  },
  {
    key: "sales-call-coaching",
    name: "Sales Call Coaching Agent",
    category: "CRM & Lead Operations",
    mission: "Analyzes a real sales call transcript the rep provides — talk-ratio, objection handling, next-step commitment — and gives specific coaching feedback, distinct from Battlecards' pre-call prep content.",
    inputs: ["Call transcript (pasted or uploaded)", "Deal stage/context if known"],
    outputs: ["Talk-ratio and pacing read", "Objection-handling assessment", "Next-step commitment check", "Specific coaching feedback"],
    wired: true,
    sortOrder: 24,
  },
  {
    key: "sales-proposal-quote",
    name: "Sales Proposal & Quote Agent",
    category: "CRM & Lead Operations",
    mission: "Drafts proposals, quotes, and SOWs for the client's OWN sales team to send to their prospects — distinct from the Freelancer & Agency Growth Proposal & 90-Day Plan agent, which serves the operator's own client-acquisition pipeline, not this client's outward-facing sales.",
    inputs: ["Deal/prospect specifics if known (scope, pricing, timeline)", "Pricing model", "ICP/personas"],
    outputs: ["Proposal/quote draft or reusable template", "Scope and pricing structure", "Follow-up next steps"],
    wired: true,
    sortOrder: 25,
  },
  {
    key: "renewal-management",
    name: "Renewal Management Agent",
    category: "CRM & Lead Operations",
    mission: "Owns the subscription renewal timeline and playbook — 90/60/30-day motion, renewal quote/contract terms, escalation triggers — distinct from Churn Prediction's risk-scoring framework and Customer Health Score's composite score, neither of which owns the renewal event itself.",
    inputs: ["Sales cycle/contract length", "Health score or churn risk signals if available", "AOV/LTV"],
    outputs: ["Renewal timeline/playbook", "Renewal quote/contract term guidance", "Risk-tier escalation triggers"],
    wired: true,
    sortOrder: 26,
  },
  {
    key: "sales-compensation-plan",
    name: "Sales Compensation / Commission Plan Agent",
    category: "CRM & Lead Operations",
    mission: "Designs rep compensation plans and quota structure tied to revenue targets — distinct from Sales Assignment & Capacity's territory/lead-routing focus, which decides who gets which leads, not how they're paid.",
    inputs: ["Revenue target", "Team size/structure", "AOV/LTV", "Sales cycle length"],
    outputs: ["Comp plan structure (base/variable split)", "Quota design", "Accelerator/clawback rules"],
    wired: true,
    sortOrder: 27,
  },
  {
    key: "deal-desk-approval",
    name: "Deal Desk & Approval Workflow Agent",
    category: "CRM & Lead Operations",
    mission: "Designs approval governance for non-standard deals — discount escalation thresholds, who approves what, turnaround SLA — distinct from Sales Proposal & Quote (drafts one specific quote) and Pricing Strategy (sets the tier/discount philosophy, not the approval workflow around exceptions to it).",
    inputs: ["Gross margin", "Team size/structure", "Pricing model"],
    outputs: ["Discount approval thresholds", "Escalation path by exception type", "Approval turnaround SLA"],
    wired: true,
    sortOrder: 28,
  },
  {
    key: "cpq-rules-design",
    name: "CPQ Rules & Bundling Agent",
    category: "CRM & Lead Operations",
    mission: "Designs the configuration, pricing, and quoting RULE ENGINE — product bundling logic, discount ladders/matrices — distinct from Sales Proposal & Quote (drafts one specific quote using these rules) and Pricing Strategy (sets tier philosophy, not the operational rule set a CPQ tool would enforce).",
    inputs: ["Product/service line-up", "Pricing model", "Gross margin"],
    outputs: ["Bundling logic", "Discount ladder/matrix", "Rule-engine structure to implement"],
    wired: true,
    sortOrder: 29,
  },
  {
    key: "channel-partner-sales",
    name: "Channel & Partner Sales Agent",
    category: "CRM & Lead Operations",
    mission: "Designs a reseller/channel partner sales program — partner tiering, deal registration to prevent channel conflict, co-selling motion — distinct from Affiliate & Partner Marketing's promotional referral-commission programs; these partners resell or implement the product, not just promote it.",
    inputs: ["Gross margin", "Pricing model", "Existing partner motion if any"],
    outputs: ["Partner tier structure", "Deal registration process", "Co-selling motion design"],
    wired: true,
    sortOrder: 30,
  },
  // Acquisition
  {
    key: "seo-strategy",
    name: "SEO Strategy Agent",
    category: "Acquisition",
    mission: "Builds keyword strategy, topic clusters, and content gap analysis for organic growth.",
    inputs: ["Website URL", "Industry", "Objective"],
    outputs: ["Keyword universe table", "Topic clusters", "Content gap opportunities", "90-day priorities"],
    wired: true,
    sortOrder: 9,
  },
  {
    key: "technical-seo",
    name: "Technical SEO Agent",
    category: "Acquisition",
    mission: "Audits crawlability, indexation, schema, internal linking, and Core Web Vitals.",
    inputs: ["Website URL"],
    outputs: ["Technical issue list", "Fix priority order"],
    wired: true,
    sortOrder: 10,
  },
  {
    key: "performance-marketing",
    name: "Performance Marketing Strategy Agent",
    category: "Acquisition",
    mission: "Recommends channel budget allocation across Google/Meta/SEO — and gives a spend-readiness verdict first, including 'don't spend yet' when fundamentals are missing.",
    inputs: ["Monthly budget & currency", "Website & tracking status", "Objective"],
    outputs: ["Spend-readiness verdict", "Budget allocation table", "Testing plan", "Kill criteria"],
    wired: true,
    sortOrder: 11,
  },
  {
    key: "google-ads",
    name: "Google Ads Agent",
    category: "Acquisition",
    mission: "Keyword research, campaign structure, bidding, and Quality Score optimization for search campaigns.",
    inputs: ["Approved paid budget", "Keyword priorities", "Landing page status"],
    outputs: ["Campaign structure", "Match type & negative keyword plan", "Bid strategy"],
    wired: true,
    sortOrder: 12,
  },
  {
    key: "meta-ads",
    name: "Meta Ads Agent",
    category: "Acquisition",
    mission: "Audience strategy, funnel design, and creative strategy for Meta campaigns.",
    inputs: ["Approved paid budget", "ICP/personas", "Creative assets"],
    outputs: ["Audience strategy", "Funnel structure", "Creative brief"],
    wired: true,
    sortOrder: 13,
  },
  {
    key: "linkedin-ads",
    name: "LinkedIn Ads Agent",
    category: "Acquisition",
    mission: "Audience, campaign structure, and creative strategy for LinkedIn campaigns, for B2B clients.",
    inputs: ["Approved paid budget", "ICP/personas (job titles, seniority)", "Objective"],
    outputs: ["Audience targeting plan", "Campaign objective/format mix", "Creative & copy angles"],
    wired: true,
    sortOrder: 130,
  },
  {
    key: "tiktok-ads",
    name: "TikTok Ads Agent",
    category: "Acquisition",
    mission: "Audience, creative, and campaign strategy for TikTok (and short-form video ad placements generally).",
    inputs: ["Approved paid budget", "ICP/personas", "Existing video/creative assets"],
    outputs: ["Audience & placement plan", "Creative concepts suited to the format", "Campaign structure"],
    wired: true,
    sortOrder: 131,
  },
  {
    key: "local-marketplace-seo",
    name: "Local & Marketplace SEO Agent",
    category: "Acquisition",
    mission: "Optimizes visibility on Google Business Profile/Maps and relevant marketplaces (app stores, Amazon, etc.) for location- or listing-based businesses.",
    inputs: ["Business type", "Website URL", "Country/region"],
    outputs: ["Listing optimization checklist", "Local ranking factors to fix", "Review/reputation plan"],
    wired: true,
    sortOrder: 132,
  },
  {
    key: "seo-blog-intelligence",
    name: "SEO Blog Intelligence & Publishing Agent",
    category: "Acquisition",
    mission: "Owns the full blog pipeline end to end — keyword, intent, SERP, competition, brief, article, on-page SEO, internal links, publish, monitor, update — optimizing for qualified traffic and conversion, never promising rankings.",
    inputs: ["SEO Strategy topic clusters", "Website URL", "Brand DNA", "Country/region"],
    outputs: ["SERP/competition analysis", "Content brief", "Full article draft", "On-page SEO checklist", "Internal linking plan", "Update/refresh triggers"],
    wired: true,
    sortOrder: 133,
  },
  {
    key: "pr-influencer",
    name: "PR & Influencer Marketing Agent",
    category: "Acquisition",
    mission: "Plans earned-media and influencer/creator partnerships to build awareness and third-party credibility.",
    inputs: ["Brand positioning", "Objective", "Budget & currency"],
    outputs: ["PR angle & story ideas", "Influencer/creator tier strategy", "Outreach plan"],
    wired: true,
    sortOrder: 134,
  },
  {
    key: "youtube-ads",
    name: "YouTube Ads Agent",
    category: "Acquisition",
    mission: "Campaign strategy for YouTube — in-stream, in-feed, Shorts ads — distinct from organic Video Marketing content.",
    inputs: ["Approved paid budget", "Video/creative assets", "Objective"],
    outputs: ["Campaign format mix", "Targeting plan", "Creative requirements"],
    wired: true,
    sortOrder: 135,
  },
  {
    key: "retargeting",
    name: "Retargeting Agent",
    category: "Acquisition",
    mission: "Cross-platform remarketing strategy — who to retarget, with what message, at what frequency — distinct from Audience & Suppression's exclusion rules.",
    inputs: ["Current channels", "Website URL", "Objective"],
    outputs: ["Retargeting audience tiers", "Message-by-tier plan", "Frequency caps"],
    wired: true,
    sortOrder: 136,
  },
  {
    key: "paid-audience-intelligence",
    name: "Paid Audience Intelligence Agent",
    category: "Acquisition",
    mission: "Researches audience opportunity across paid platforms before campaigns launch — sizing, overlap, and untapped segments.",
    inputs: ["ICP/personas", "Industry", "Current channels"],
    outputs: ["Audience opportunity map", "Segment prioritization", "Platform fit per segment"],
    wired: true,
    sortOrder: 137,
  },
  {
    key: "paid-media-optimization",
    name: "Paid Media Optimization Agent",
    category: "Acquisition",
    mission: "Cross-channel budget optimization across all active paid channels — where to scale, where to pause — once multiple paid agents are running.",
    inputs: ["Run history across paid agents", "Monthly budget & currency", "Targets"],
    outputs: ["Scale/pause recommendations by channel", "Reallocation plan", "Kill criteria review"],
    wired: true,
    sortOrder: 138,
  },
  {
    key: "marketplace-seo",
    name: "Marketplace SEO Agent",
    category: "Acquisition",
    mission: "Optimizes visibility on non-search marketplaces — app stores, Amazon, Etsy, category marketplaces — distinct from Local & Marketplace SEO's Google Business Profile/Maps focus.",
    inputs: ["Business type", "Product type", "Country/region"],
    outputs: ["Marketplace listing optimization checklist", "Marketplace-specific ranking factors", "Review/rating strategy per marketplace"],
    wired: true,
    sortOrder: 139,
  },
  {
    key: "seo-content-strategy",
    name: "SEO Content Strategy Agent",
    category: "Acquisition",
    mission: "Decides which content should be created specifically to win organic, keyword-driven growth — narrower than the general Content Strategy Agent's whole-funnel content remit.",
    inputs: ["SEO Strategy topic clusters", "Website URL", "Objective"],
    outputs: ["Keyword-to-content mapping", "Organic content priority order", "Cluster coverage gaps"],
    wired: true,
    sortOrder: 140,
  },
  {
    key: "affiliate-partner-marketing",
    name: "Affiliate & Partner Marketing Agent",
    category: "Acquisition",
    mission: "Designs affiliate/partner programs — commission structure, partner recruitment, tracking needs — distinct from Referral's customer-to-customer focus; this is third-party partners promoting for commission.",
    inputs: ["AOV/LTV", "Gross margin", "Budget & currency"],
    outputs: ["Commission structure", "Partner recruitment criteria", "Tracking/attribution requirements"],
    wired: true,
    sortOrder: 141,
  },
  // Content & Creative
  {
    key: "content-strategy",
    name: "Content Strategy Agent",
    category: "Content & Creative",
    mission: "Decides what content to create, for whom, at which funnel stage, and in what format.",
    inputs: ["ICP/personas", "SEO topic clusters", "Objective"],
    outputs: ["Content pillars", "Editorial calendar shape", "Format & channel map"],
    wired: true,
    sortOrder: 14,
  },
  {
    key: "content-creation",
    name: "Content Creation Agent",
    category: "Content & Creative",
    mission: "Writes blog, landing page, ad, and email copy from strategy, ICP, SEO, and brand inputs.",
    inputs: ["Content strategy", "Brand voice", "SEO targets"],
    outputs: ["Draft copy by asset type"],
    wired: true,
    sortOrder: 15,
  },
  {
    key: "content-repurposing",
    name: "Content Repurposing Agent",
    category: "Content & Creative",
    mission: "Converts one core content asset into LinkedIn, Instagram, email, and short-form variants.",
    inputs: ["Source asset", "Target channels"],
    outputs: ["Per-channel repurposed variants"],
    wired: true,
    sortOrder: 16,
  },
  {
    key: "brand-creative-strategy",
    name: "Brand & Creative Strategy Agent",
    category: "Content & Creative",
    mission: "Defines positioning, brand personality, messaging, and creative direction.",
    inputs: ["Business model", "ICP", "Competitor positioning"],
    outputs: ["Brand voice guide", "Positioning statement", "Creative direction notes"],
    wired: true,
    sortOrder: 17,
  },
  {
    key: "design",
    name: "Design Agent",
    category: "Content & Creative",
    mission: "Produces ad, social, landing page, and email creative briefs that follow Brand DNA.",
    inputs: ["Brand guide", "Campaign brief"],
    outputs: ["Creative asset briefs"],
    wired: true,
    sortOrder: 18,
  },
  {
    key: "video-marketing",
    name: "Video Marketing Agent",
    category: "Content & Creative",
    mission: "Develops video concepts, hooks, and scripts for reels, shorts, and YouTube.",
    inputs: ["Content strategy", "Brand voice", "Target channel"],
    outputs: ["Video concepts & scripts"],
    wired: true,
    sortOrder: 19,
  },
  {
    key: "brand-identity-logo",
    name: "Brand Identity & Logo Agent",
    category: "Content & Creative",
    mission: "Defines logo direction, color system, and typography — the visual identity layer above Brand & Creative Strategy's positioning work.",
    inputs: ["Brand personality", "Industry", "Positioning"],
    outputs: ["Logo concept direction", "Color palette", "Typography system"],
    wired: true,
    sortOrder: 20,
  },
  {
    key: "creative-director",
    name: "Creative Director Agent",
    category: "Content & Creative",
    mission: "Defines the creative concept a campaign should execute — the unifying idea before Design produces individual assets.",
    inputs: ["Campaign brief", "Brand DNA", "Objective"],
    outputs: ["Creative concept", "Concept rationale", "Asset requirements by channel"],
    wired: true,
    sortOrder: 21,
  },
  {
    key: "creative-qa",
    name: "Creative QA Agent",
    category: "Content & Creative",
    mission: "Checks creative assets and copy against Brand DNA and compliance basics before they ship — a review pass, not a creation pass.",
    inputs: ["Asset/copy to review", "Brand DNA"],
    outputs: ["Brand compliance check", "Issues found", "Approve/revise verdict"],
    wired: true,
    sortOrder: 22,
  },
  {
    key: "social-media",
    name: "Social Media Agent",
    category: "Content & Creative",
    mission: "Plans organic social posting strategy and calendar shape across platforms — distinct from paid social (Meta/LinkedIn/TikTok Ads) and Content Repurposing's per-asset adaptation.",
    inputs: ["Content strategy", "Current channels", "Brand DNA"],
    outputs: ["Platform-by-platform posting cadence", "Content pillar mix", "Engagement tactics"],
    wired: true,
    sortOrder: 23,
  },
  {
    key: "influencer-creator-marketing",
    name: "Influencer / Creator Marketing Agent",
    category: "Content & Creative",
    mission: "Plans creator/influencer partnerships specifically — distinct from PR & Influencer Marketing's earned-media/press focus, this one is dedicated to the creator-partnership motion alone.",
    inputs: ["Brand positioning", "ICP/personas", "Budget & currency"],
    outputs: ["Creator tier & niche targeting", "Partnership structure (gifted vs paid vs affiliate)", "Content brief for creators"],
    wired: true,
    sortOrder: 24,
  },
  {
    key: "image-generation",
    name: "Image Generation Agent",
    category: "Content & Creative",
    mission: "Actually generates a real image from a brief — the first agent in this system that produces media, not just advice — using a free, unlimited generation model, distinct from Design Agent's advisory visual-direction guidance.",
    inputs: ["Image brief (optional — falls back to a generic on-brand image)", "Brand DNA", "ICP/personas"],
    outputs: ["Engineered generation prompt", "Generated image"],
    wired: true,
    sortOrder: 25,
  },
  // Digital Experience
  {
    key: "website-builder",
    name: "Website Builder Agent",
    category: "Digital Experience",
    mission: "Plans website architecture, UX, and page structure when no site or a weak site exists.",
    inputs: ["Business model", "ICP", "SEO structure"],
    outputs: ["Site map", "Page-by-page content brief"],
    wired: true,
    sortOrder: 20,
  },
  {
    key: "landing-page",
    name: "Landing Page Agent",
    category: "Digital Experience",
    mission: "Builds campaign- and SEO-specific landing pages optimized for conversion.",
    inputs: ["Campaign objective", "ICP", "Offer"],
    outputs: ["Landing page brief & copy structure"],
    wired: true,
    sortOrder: 21,
  },
  {
    key: "cro",
    name: "CRO Agent",
    category: "Digital Experience",
    mission: "Diagnoses funnel leakage — visitor to lead to sale — and recommends conversion fixes.",
    inputs: ["Funnel data", "Website URL", "Current conversion rate"],
    outputs: ["Funnel leak diagnosis", "Prioritized fix list"],
    wired: true,
    sortOrder: 22,
  },
  {
    key: "funnel-intelligence",
    name: "Funnel Intelligence Agent",
    category: "Digital Experience",
    mission: "Maps and quantifies the conversion funnel stage by stage, distinct from CRO's fix-prioritization role — this one measures, CRO fixes.",
    inputs: ["Website URL", "Current channels", "Run history"],
    outputs: ["Funnel stage map", "Stage-by-stage drop-off estimate", "Where to instrument next"],
    wired: true,
    sortOrder: 23,
  },
  {
    key: "web-personalization",
    name: "Web Personalization Agent",
    category: "Digital Experience",
    mission: "Designs on-site personalization rules — different messaging by traffic source, returning vs new visitor, funnel stage.",
    inputs: ["Current channels", "ICP/personas", "Website URL"],
    outputs: ["Personalization rule set", "Segment-by-segment messaging", "Priority order to implement"],
    wired: true,
    sortOrder: 24,
  },
  {
    key: "conversion-experiment",
    name: "Conversion Experiment Agent",
    category: "Digital Experience",
    mission: "Designs specific CRO A/B tests — hypothesis, variant, success metric — distinct from Marketing Analytics' broader experimentation remit.",
    inputs: ["CRO findings", "Website URL", "Run history"],
    outputs: ["Test hypothesis", "Control/variant spec", "Success threshold & duration"],
    wired: true,
    sortOrder: 25,
  },
  {
    key: "website-strategy",
    name: "Website Strategy Agent",
    category: "Digital Experience",
    mission: "Defines site architecture and page strategy at a planning level — the plan Website Builder then executes into actual page briefs.",
    inputs: ["Business model", "SEO Strategy topic clusters", "Objective"],
    outputs: ["Site architecture plan", "Page-type strategy (which page types exist and why)", "Priority build order"],
    wired: true,
    sortOrder: 26,
  },
  {
    key: "digital-experience-ux",
    name: "Digital Experience / UX Agent",
    category: "Digital Experience",
    mission: "Reviews overall user-experience quality across digital touchpoints — distinct from CRO's conversion-fix focus and Funnel Intelligence's stage-by-stage measurement.",
    inputs: ["Website URL", "Current channels", "ICP/personas"],
    outputs: ["UX quality assessment", "Usability issues by touchpoint", "Accessibility/mobile considerations"],
    wired: true,
    sortOrder: 27,
  },
  {
    key: "landing-page-split-test",
    name: "Landing Page Split-Test Agent",
    category: "Digital Experience",
    mission: "Designs a landing page split test — one master/control page compared against multiple full-page variant designs — to find the best-performing whole-page approach, distinct from Conversion Experiment's single-hypothesis, element-level CRO test design.",
    inputs: ["Master/control landing page or brief", "Campaign objective", "Traffic volume if known"],
    outputs: ["Master page summary", "Multiple full-page variant concepts with what differs and why", "Traffic split plan", "Success metric and required sample size"],
    wired: true,
    sortOrder: 28,
  },
  {
    key: "website-technology-structure",
    name: "Website Technology & Structure Agent",
    category: "Digital Experience",
    mission: "Real, live audit of a client's website — actual technology stack detected via signature matching (CMS, framework, analytics, forms, CDN) and actual subpages discovered via robots.txt/sitemap (following the declared sitemap, not just guessing the conventional path) or link crawling — then classifies each discovered page as a per-offering Landing Page vs. a structural Site Page, and interprets what the findings mean for the marketing stack. Distinct from Technical SEO's crawlability focus and the standalone Domain Scan tool's raw, unopinionated output.",
    inputs: ["Website URL"],
    outputs: ["Detected technology stack by category", "Landing page groups vs. site structure pages (classified, with counts)", "Full raw discovered-page list (guaranteed complete, appended separately)", "Gaps and integration opportunities"],
    wired: true,
    sortOrder: 29,
  },
  {
    key: "url-reputation-blocklist-check",
    name: "URL Security & Reputation Agent",
    category: "Digital Experience",
    mission: "Checks two genuinely different ways a URL can be blocked: flagged as malicious by antivirus/browser security vendors (Google Safe Browsing, Norton, VirusTotal, McAfee), or miscategorized by a corporate web-filter product (Palo Alto, ESET, Cisco Talos, Bitdefender) — real one-click links to each vendor's own free checker, since no free automated cross-vendor API exists without violating that vendor's own terms of service. Explains the key distinction: a workplace category block is almost always the viewer's own IT policy (contact them directly), while a public reputation flag or broad miscategorization is something the site owner requests a vendor review for. Advisory on remediation, not an automated firewall/antivirus configuration change — this system has no access to modify security infrastructure, and never would.",
    inputs: ["Website/landing page URL", "What you're seeing if already flagged (optional)"],
    outputs: ["Real one-click reputation-check links (Google Safe Browsing, Norton Safe Web, VirusTotal, McAfee)", "Real one-click web-filter category-check links (Palo Alto, ESET, Cisco Talos, Bitdefender)", "Vendor-specific remediation/reconsideration steps", "Prevention checklist"],
    wired: true,
    sortOrder: 30,
  },
  // Retention & Lifecycle
  {
    key: "email-marketing",
    name: "Email Marketing Agent",
    category: "Retention & Lifecycle",
    mission: "Designs lifecycle email flows (welcome, nurture, abandonment, win-back) and campaign sends that turn subscribers into customers and customers into repeat customers.",
    inputs: ["Objective", "ICP/personas", "Current channels & assets"],
    outputs: ["Lifecycle flow map", "Flow-by-flow email sequence briefs", "Subject line angles"],
    wired: true,
    sortOrder: 1,
  },
  {
    key: "email-deliverability",
    name: "Email Compliance, Deliverability & Performance Agent",
    category: "Retention & Lifecycle",
    mission: "Diagnoses sender reputation and deliverability risk (SPF/DKIM/DMARC/BIMI, bounce rate, spam-trap risk, list hygiene) and flags consent/compliance gaps — works alongside Email Marketing, not instead of it.",
    inputs: ["Website/domain", "Current channels", "Country/region"],
    outputs: ["Authentication checklist", "Deliverability risk assessment", "Compliance flags by jurisdiction"],
    wired: true,
    sortOrder: 2,
  },
  {
    key: "whatsapp-sms-marketing",
    name: "WhatsApp & SMS Marketing Agent",
    category: "Retention & Lifecycle",
    mission: "Designs WhatsApp/SMS messaging flows for time-sensitive updates, reminders, and conversational sales — for businesses where buyers expect fast, direct contact.",
    inputs: ["Objective", "Current channels", "Country/region"],
    outputs: ["Message flow map", "Template message drafts", "Opt-in & compliance notes"],
    wired: true,
    sortOrder: 3,
  },
  {
    key: "conversational-ai-appointment",
    name: "Conversational AI & Appointment Agent",
    category: "Retention & Lifecycle",
    mission: "Designs chatbot/voicebot qualification flows, missed-call recovery, and appointment scheduling/reminder logic for businesses that convert via booking or a live conversation.",
    inputs: ["Objective", "Current channels", "Business model"],
    outputs: ["Qualification flow", "Booking/reminder flow", "Escalation-to-human rules"],
    wired: true,
    sortOrder: 4,
  },
  {
    key: "omnichannel-orchestration",
    name: "Omnichannel & Next-Best-Channel Agent",
    category: "Retention & Lifecycle",
    mission: "Decides which channel to try next for an individual lead or customer (email → WhatsApp → voice → push → retargeting) based on consent, past engagement, urgency, and cost — the sequencing brain above the individual channel agents.",
    inputs: ["Current channels", "Objective", "Run history"],
    outputs: ["Channel escalation sequence", "Fallback rules per stage", "Cost/urgency tradeoffs"],
    wired: true,
    sortOrder: 5,
  },
  {
    key: "lifecycle-nurture",
    name: "Lifecycle & Nurture Strategy Agent",
    category: "Retention & Lifecycle",
    mission: "Defines the welcome/nurture/activation/re-engagement/win-back journey a customer should move through, independent of which channel executes each step.",
    inputs: ["Objective", "ICP/personas", "Current channels"],
    outputs: ["Lifecycle stage map", "Trigger-by-stage journey", "Channel-agnostic content briefs per stage"],
    wired: true,
    sortOrder: 6,
  },
  {
    key: "referral-loyalty",
    name: "Referral & Loyalty Agent",
    category: "Retention & Lifecycle",
    mission: "Designs referral programs and loyalty mechanics that turn existing customers into a repeatable, low-cost acquisition channel.",
    inputs: ["Objective", "Existing customer base signal", "Budget & currency"],
    outputs: ["Referral program mechanics", "Loyalty tier structure", "Launch messaging"],
    wired: true,
    sortOrder: 7,
  },
  {
    key: "rcs-marketing",
    name: "RCS Marketing Agent",
    category: "Retention & Lifecycle",
    mission: "Designs Rich Communication Services messaging flows where RCS is viable — richer than SMS, distinct from WhatsApp's ecosystem.",
    inputs: ["Country/region", "Current channels", "Objective"],
    outputs: ["RCS viability check", "Message flow map", "Fallback to SMS rules"],
    wired: true,
    sortOrder: 8,
  },
  {
    key: "voicebot",
    name: "Voicebot Agent",
    category: "Retention & Lifecycle",
    mission: "Designs automated voice call flows — outbound reminders, inbound IVR qualification — distinct from Conversational AI & Appointment's chat/booking focus.",
    inputs: ["Business model", "Current channels", "Country/region"],
    outputs: ["Call flow script", "Escalation-to-human triggers", "Use-case fit check"],
    wired: true,
    sortOrder: 9,
  },
  {
    key: "push-notification",
    name: "Push Notification Agent",
    category: "Retention & Lifecycle",
    mission: "Designs web and mobile push notification strategy — re-engagement triggers, timing, message brevity — for businesses with an app or PWA.",
    inputs: ["Business model", "Current channels", "Objective"],
    outputs: ["Push trigger map", "Message drafts", "Frequency/fatigue guardrails"],
    wired: true,
    sortOrder: 10,
  },
  {
    key: "in-app-notification",
    name: "In-App Notification Agent",
    category: "Retention & Lifecycle",
    mission: "Designs in-app messaging tied to product usage events — onboarding nudges, feature discovery, upgrade prompts — for SaaS/app clients.",
    inputs: ["Business model", "Objective", "Current channels"],
    outputs: ["Usage-triggered message map", "Message drafts", "Placement recommendations"],
    wired: true,
    sortOrder: 11,
  },
  {
    key: "retention-intelligence",
    name: "Retention Intelligence Agent",
    category: "Retention & Lifecycle",
    mission: "Analyzes retention patterns and risk signals — distinct from Churn Prediction's forward-looking scoring — this one explains what's already happening.",
    inputs: ["Retention target", "Run history", "Business model"],
    outputs: ["Retention pattern read", "Likely at-risk segments", "Retention lever priorities"],
    wired: true,
    sortOrder: 12,
  },
  {
    key: "churn-prediction",
    name: "Churn Prediction Agent",
    category: "Retention & Lifecycle",
    mission: "Defines the churn-risk scoring framework — signals and thresholds — advisory model design, not a live prediction on real customer data.",
    inputs: ["Business model", "Retention target", "Current channels"],
    outputs: ["Churn signal list", "Scoring framework", "Intervention triggers by risk tier"],
    wired: true,
    sortOrder: 13,
  },
  {
    key: "upsell-cross-sell",
    name: "Upsell & Cross-sell Agent",
    category: "Retention & Lifecycle",
    mission: "Identifies expansion revenue opportunities in the existing customer base and designs the offer/messaging to capture them.",
    inputs: ["Business model", "AOV/LTV", "Existing customer base signal"],
    outputs: ["Expansion opportunity map", "Offer design", "Trigger-based messaging plan"],
    wired: true,
    sortOrder: 14,
  },
  {
    key: "customer-experience-reputation",
    name: "Customer Experience & Reputation Agent",
    category: "Retention & Lifecycle",
    mission: "Analyzes review/rating/sentiment patterns and designs a reputation-building plan — advisory, since this system has no live review-platform connection.",
    inputs: ["Business model", "Country/region", "Current channels"],
    outputs: ["Reputation risk assessment", "Review-generation plan", "Common complaint themes to address"],
    wired: true,
    sortOrder: 15,
  },
  {
    key: "lead-nurturing-strategy",
    name: "Lead Nurturing Strategy Agent",
    category: "CRM & Lead Operations",
    mission: "Pre-conversion nurture strategy specifically for leads not yet customers — distinct from Lifecycle & Nurture's whole-customer-lifecycle remit, which includes post-purchase stages.",
    inputs: ["ICP/personas", "Objective", "Lead scoring model if available"],
    outputs: ["Pre-conversion nurture stage map", "Lead-stage-specific messaging goals", "Hand-off point to sales"],
    wired: true,
    sortOrder: 31,
  },
  {
    key: "whatsapp-marketing",
    name: "WhatsApp Marketing Agent",
    category: "Retention & Lifecycle",
    mission: "WhatsApp-specific messaging flows, catalogs, and Business API features — deeper platform-specific treatment than the combined WhatsApp & SMS Marketing Agent provides.",
    inputs: ["Objective", "Country/region", "Business model"],
    outputs: ["WhatsApp-specific flow map", "Catalog/product message structure if relevant", "Business API feature recommendations"],
    wired: true,
    sortOrder: 17,
  },
  {
    key: "sms-marketing",
    name: "SMS Marketing Agent",
    category: "Retention & Lifecycle",
    mission: "SMS-specific messaging flows — distinct constraints from WhatsApp (character limits, carrier filtering, regional SMS regulation) get their own dedicated treatment here.",
    inputs: ["Objective", "Country/region", "Current channels"],
    outputs: ["SMS-specific flow map", "Character-constrained message drafts", "Regional compliance notes"],
    wired: true,
    sortOrder: 18,
  },
  {
    key: "chatbot-conversational-ai",
    name: "Chatbot / Conversational AI Agent",
    category: "Retention & Lifecycle",
    mission: "General website/app chat and FAQ handling — distinct from Conversational AI & Appointment's booking-specific focus, this covers support and pre-sale questions broadly.",
    inputs: ["Business model", "Current channels", "ICP/personas"],
    outputs: ["FAQ/support flow map", "Escalation-to-human rules", "Common question coverage"],
    wired: true,
    sortOrder: 19,
  },
  {
    key: "loyalty",
    name: "Loyalty Agent",
    category: "Retention & Lifecycle",
    mission: "Loyalty program mechanics specifically — tiers, points, perks — distinct from Referral & Loyalty's combined referral focus.",
    inputs: ["Objective", "AOV/LTV", "Existing customer base signal"],
    outputs: ["Loyalty tier structure", "Points/perk mechanics", "Launch messaging"],
    wired: true,
    sortOrder: 20,
  },
  {
    key: "referral",
    name: "Referral Agent",
    category: "Retention & Lifecycle",
    mission: "Referral program mechanics specifically — incentive structure, sharing flow — distinct from Referral & Loyalty's combined loyalty focus.",
    inputs: ["Objective", "Existing customer base signal", "Budget & currency"],
    outputs: ["Referral incentive structure", "Sharing/invite flow", "Launch messaging"],
    wired: true,
    sortOrder: 21,
  },
  {
    key: "customer-health-score",
    name: "Customer Health Score Agent",
    category: "Retention & Lifecycle",
    mission: "Defines a composite health score (usage + support + billing + engagement) for subscription/SaaS clients — broader than Churn Prediction's risk-only lens, this is the ongoing account-health signal Customer Success teams live by.",
    inputs: ["Business model", "Retention target", "Current channels"],
    outputs: ["Health score composite formula", "Score tiers & triggers", "Owner (CS vs. marketing) per tier"],
    wired: true,
    sortOrder: 22,
  },
  // Marketing Operations
  {
    key: "marketing-tracking-integration",
    name: "Marketing Tracking & Integration Agent",
    category: "Marketing Operations",
    mission: "Identifies what tracking (GTM, GA4, Google Ads conversions, Meta Pixel/CAPI, offline conversions, UTM governance) a client needs and what's likely missing — advisory diagnosis, not a live tag audit or a real GTM/GA4 connection.",
    inputs: ["Website URL", "Current channels", "Monthly budget & currency"],
    outputs: ["Tracking gap diagnosis", "Conversion event mapping plan", "UTM governance rules"],
    wired: true,
    sortOrder: 1,
  },
  {
    key: "audience-suppression",
    name: "Audience & Suppression Agent",
    category: "Marketing Operations",
    mission: "Designs audience governance — who to exclude from acquisition campaigns (existing customers, converted leads), who to build lookalikes from, and how audiences should sync to Google/Meta — advisory rule design, not a live audience sync.",
    inputs: ["Current channels", "Objective", "Existing customer base signal"],
    outputs: ["Suppression list rules", "Lookalike seed criteria", "Audience sync plan"],
    wired: true,
    sortOrder: 2,
  },
  {
    key: "marketing-automation-workflow",
    name: "Marketing Automation & Workflow Agent",
    category: "Marketing Operations",
    mission: "Designs the trigger → condition → action workflow logic connecting lead capture, scoring, and channel hand-offs — advisory workflow design (the kind you'd build in a CRM automation builder or n8n/Make/Zapier), not a live automation engine.",
    inputs: ["Current channels", "Objective", "Business model"],
    outputs: ["Workflow diagrams (trigger/condition/action)", "Recommended automation tooling", "Edge cases to handle"],
    wired: true,
    sortOrder: 3,
  },
  {
    key: "event-conversion-mapping",
    name: "Event & Conversion Mapping Agent",
    category: "Marketing Operations",
    mission: "Defines the universal event model — what counts as a conversion, at what value, mapped consistently across platforms — the schema Marketing Tracking & Integration implements.",
    inputs: ["Objective", "Current channels", "Revenue target"],
    outputs: ["Event taxonomy", "Conversion value mapping", "Cross-platform consistency rules"],
    wired: true,
    sortOrder: 4,
  },
  {
    key: "utm-campaign-taxonomy",
    name: "UTM & Campaign Taxonomy Agent",
    category: "Marketing Operations",
    mission: "Defines the campaign naming and UTM convention this client should use consistently across every channel — prevents fragmented reporting.",
    inputs: ["Current channels", "Objective"],
    outputs: ["UTM parameter convention", "Campaign naming rules", "Examples by channel"],
    wired: true,
    sortOrder: 5,
  },
  {
    key: "integration-management",
    name: "Integration Management Agent",
    category: "Marketing Operations",
    mission: "Recommends which third-party tools (CRM, email, WhatsApp provider, forms) this client should connect and in what order — advisory recommendation, not a live OAuth connection to any platform.",
    inputs: ["Existing stack", "Business model", "Current channels"],
    outputs: ["Recommended integration stack", "Connection priority order", "Known limitations of each option"],
    wired: true,
    sortOrder: 6,
  },
  {
    key: "marketing-compliance-governance",
    name: "Marketing Compliance & Governance Agent",
    category: "Marketing Operations",
    mission: "Centralizes policy across data privacy, consent, advertising rules, brand claims, and communication compliance — a policy layer other agents should defer to, not a replacement for legal advice.",
    inputs: ["Country/region", "Current channels", "Industry"],
    outputs: ["Applicable regulatory framework checklist", "Consent & data-privacy requirements", "Advertising/claims restrictions by channel", "Audit trail recommendations"],
    wired: true,
    sortOrder: 8,
  },
  {
    key: "audience-sync-offline-conversion",
    name: "Audience Sync & Offline Conversion Agent",
    category: "Marketing Operations",
    mission: "Defines the sync mechanics and offline-conversion upload process specifically — distinct from Audience & Suppression's broader exclusion-list governance, this one is about the technical sync/upload pipeline.",
    inputs: ["Current channels", "Existing stack", "Revenue target"],
    outputs: ["Audience sync schedule/method", "Offline conversion upload process", "Data matching requirements"],
    wired: true,
    sortOrder: 7,
  },
  // Intelligence & Measurement
  {
    key: "lead-behaviour",
    name: "Lead Behaviour & Conversion Intelligence Agent",
    category: "CRM & Lead Operations",
    mission: "Analyzes individual lead behavior across channels to produce conversion probability and next-best-action.",
    inputs: ["Lead activity data", "CRM stage", "Channel source"],
    outputs: ["Conversion probability", "Primary barrier", "Next-best-action"],
    wired: true,
    sortOrder: 32,
  },
  {
    key: "marketing-analytics",
    name: "Marketing Analytics & Experimentation Agent",
    category: "Intelligence & Measurement",
    mission: "Tracks funnel, channel, and campaign performance, and designs A/B tests with control/treatment and success thresholds.",
    inputs: ["Run history", "Channel spend & results"],
    outputs: ["Performance dashboard summary", "Experiment plan"],
    wired: true,
    sortOrder: 24,
  },
  {
    key: "marketing-score",
    name: "Marketing Score & AI Evaluation Agent",
    category: "Intelligence & Measurement",
    mission: "Scores prediction accuracy and business impact across all agents using the predicted-vs-actual outcome log — the system's evaluation loop.",
    inputs: ["All agent_runs with predicted + actual outcomes"],
    outputs: ["Per-agent accuracy score", "Overall marketing health score", "Trend over time"],
    wired: true,
    sortOrder: 25,
  },
  {
    key: "experimentation",
    name: "Experimentation Agent",
    category: "Intelligence & Measurement",
    mission: "Designs the general cross-channel experimentation program — backlog, prioritization, velocity — distinct from Conversion Experiment's CRO-specific single-test design and Marketing Analytics' performance-tracking focus.",
    inputs: ["Run history", "Objective", "Marketing Score data"],
    outputs: ["Experiment backlog", "Prioritization framework (e.g. ICE/PIE)", "Experimentation velocity target"],
    wired: true,
    sortOrder: 26,
  },
  {
    key: "customer-segmentation",
    name: "Customer Segmentation Agent",
    category: "Intelligence & Measurement",
    mission: "Builds behavioral/RFM segmentation models for existing customers, for lifecycle targeting — distinct from pre-sale ICP work and from Lead Scoring's pre-conversion focus.",
    inputs: ["Existing customer base signal", "AOV/LTV", "Run history"],
    outputs: ["Segmentation model (RFM or behavioral)", "Segment definitions", "Segment-specific strategy implications"],
    wired: true,
    sortOrder: 27,
  },
  {
    key: "attribution",
    name: "Attribution Agent",
    category: "Intelligence & Measurement",
    mission: "Answers where results came from — applies a stated attribution model to explain channel contribution, distinct from Revenue Attribution's CRM-side credit rules.",
    inputs: ["Run history", "Current channels", "Objective"],
    outputs: ["Channel contribution read", "Attribution model used & why", "Confidence caveats"],
    wired: true,
    sortOrder: 26,
  },
  {
    key: "incrementality",
    name: "Incrementality Agent",
    category: "Intelligence & Measurement",
    mission: "Answers whether an intervention actually caused an improvement — designs holdout/geo-lift style tests rather than assuming correlation is causation.",
    inputs: ["Run history", "Current channels", "Marketing Score data"],
    outputs: ["Incrementality test design", "What correlation-only evidence is misleading here", "Recommended holdout structure"],
    wired: true,
    sortOrder: 27,
  },
  {
    key: "cohort-funnel-intelligence",
    name: "Cohort & Funnel Intelligence Agent",
    category: "Intelligence & Measurement",
    mission: "Analyzes performance by cohort (signup month, channel, campaign) to surface patterns aggregate metrics hide.",
    inputs: ["Run history", "Objective", "Retention target"],
    outputs: ["Cohort analysis framework", "Patterns to watch for", "Reporting cadence recommendation"],
    wired: true,
    sortOrder: 28,
  },
  {
    key: "ai-learning-memory",
    name: "AI Learning / Marketing Memory Agent",
    category: "Intelligence & Measurement",
    mission: "Turns this workspace's historical agent runs and outcomes into reusable business intelligence — what's worked, what hasn't, and why — the system's long-term memory layer.",
    inputs: ["Full run history with outcomes", "Marketing Score data"],
    outputs: ["Patterns that worked", "Patterns that failed", "Recommendations to carry into the next planning cycle"],
    wired: true,
    sortOrder: 29,
  },
  // Freelancer & Agency Growth
  {
    key: "prospect-discovery",
    name: "Prospect Discovery Agent",
    category: "Freelancer & Agency Growth",
    mission: "Identifies the profile of potential clients worth pursuing from permitted public/business information — advisory targeting criteria, not a live scraping/discovery tool.",
    inputs: ["Agency's own ICP", "Target industry", "Target geography"],
    outputs: ["Ideal prospect profile", "Where to find them", "Disqualifying signals"],
    wired: true,
    sortOrder: 1,
  },
  {
    key: "prospect-digital-audit",
    name: "Prospect Digital Audit Agent",
    category: "Freelancer & Agency Growth",
    mission: "Audits a prospective client's digital presence — website, SEO, ads, CRM, booking, follow-up, reputation — to find the opportunity, from what's knowable without live access.",
    inputs: ["Prospect website URL", "Prospect industry", "Prospect country/region"],
    outputs: ["Digital maturity assessment", "Gap list by category", "Evidence vs assumption labeling"],
    wired: true,
    sortOrder: 2,
  },
  {
    key: "prospect-opportunity-scoring",
    name: "Prospect Opportunity Scoring Agent",
    category: "Freelancer & Agency Growth",
    mission: "Scores a prospect's opportunity size and win-likelihood from the digital audit findings — ranges and confidence, never invented revenue-loss numbers.",
    inputs: ["Prospect Digital Audit output", "Agency's service offering", "Prospect business size signals"],
    outputs: ["Opportunity score", "Estimated impact range (labeled as estimate)", "Fit confidence"],
    wired: true,
    sortOrder: 3,
  },
  {
    key: "proposal-90-day-plan",
    name: "Proposal & 90-Day Plan Agent",
    category: "Freelancer & Agency Growth",
    mission: "Turns a scored prospect into a client-ready proposal with a concrete 90-day plan — assumptions stated, not invented certainty.",
    inputs: ["Prospect Opportunity Scoring output", "Agency's service offering", "Pricing"],
    outputs: ["Client-ready proposal draft", "90-day plan", "Assumptions & risks section"],
    wired: true,
    sortOrder: 4,
  },
  {
    key: "client-reporting-white-label",
    name: "Client Reporting / White-label Agent",
    category: "Freelancer & Agency Growth",
    mission: "Generates client-facing performance reports from this workspace's run and outcome history, formatted for an agency to present under its own brand.",
    inputs: ["Run history", "Marketing Score data", "Agency branding preference"],
    outputs: ["Client-facing report draft", "Key wins to highlight", "Honest framing of misses"],
    wired: true,
    sortOrder: 5,
  },
];

export function getAgentSpec(key: string): AgentSpec | undefined {
  return AGENT_CATALOG.find((a) => a.key === key);
}
